### ISSUE TITLE
Redirect https://carpentries-incubator.github.io to https://carpentries-incubator.org?

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/carpentries-incubator.org#21]
Is it worth redirecting https://carpentries-incubator.github.io to https://carpentries-incubator.org?

Solves the problem where people (like me) try to return to the home page by shortening a URL.

Probably easy with a new `gh-pages` branch including a single extra `index.html` file to redirect, as here: https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7

**Comment by tobyhodges** [comment]
Thank you for this very sensible suggestion @ewallace, which I somehow missed until today. I have implemented the redirect now (FYI @fmichonneau).
